//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by KDSManager.rc
//
#define IDD_KDSMANAGER_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDD_DLG_ITEM                    129
#define IDD_DLG_ITEM_DETAIL             129
#define IDS_STR_GOBACK_COOK             130
#define IDS_STR_GOBACK_SEND             131
#define IDS_STR_RECOVERY                132
#define IDS_STR_ORDER                   133
#define IDS_STR_PENDING                 134
#define IDS_STR_DONE                    135
#define IDD_DIALOG1                     136
#define IDD_DLG_SETTING                 136
#define IDS_STR_PAGENUM                 136
#define IDS_STR_HISTORYLIST             137
#define IDD_DLG_ORDER                   137
#define IDS_STR_PENDLIST                138
#define IDD_DLG_ITEM_ORDER              138
#define IDS_STR_FIRST                   139
#define IDS_STR_PRE                     140
#define IDS_STR_NEXT                    141
#define IDS_STR_END                     142
#define IDS_STR_CLOSE                   143
#define IDS_STR_AVGTIME                 144
#define IDS_STR_SETTING                 145
#define IDS_STR_QUANTITY                146
#define IDS_STR_COOKING                 147
#define IDS_STR_COOKED                  148
#define IDS_STR_SENDED                  149
#define IDS_STR_REGMSG                  150
#define IDD_DLG_LANGSELECT              150
#define IDS_STR_NOTVALID                151
#define IDD_DLG_ORDERFUNCTION           151
#define IDS_STR_GUOQI                   152
#define IDS_STR_NOTTHISMACH             153
#define IDD_DLG_COMBINE                 153
#define IDS_STR_NOTREG                  154
#define IDD_DLG_ITEM_DETAILNEW2         154
#define IDS_EXPIER                      155
#define IDS_STR_NUM                     156
#define IDS_STR_UNIT                    157
#define IDS_STR_DESC                    158
#define IDS_STR_REMARK                  159
#define IDS_STR_EATTYPE                 160
#define IDI_ICON1                       160
#define IDS_STR_OPENEMPLOYEE            161
#define IDS_STR_POS                     162
#define IDS_STR_ORDERTIME               163
#define IDS_STR_HEADID                  164
#define IDS_STR_CHECKNUM                165
#define IDS_STR_CHECKNAME               166
#define IDS_STR_TABLE                   167
#define IDS_STR_CUSTNUM                 168
#define IDS_STR_KDSTIME                 169
#define IDS_STR_CUSTNUM4                170
#define IDS_STR_KDSSTYLE                171
#define IDS_STR_KDSMODE                 172
#define IDS_STR_REFRESHTIME             173
#define IDS_STR_STALL                   174
#define IDS_STR_KITCHEN                 175
#define IDS_STR_SEND                    176
#define IDS_STR_DETAIL                  177
#define IDS_STR_BYDETAIL                177
#define IDS_STR_BYORDER                 178
#define IDS_STR_SAVE                    179
#define IDS_STR_CANCEL                  180
#define IDS_STR_TAKEOUT2                181
#define IDS_STR_TAKEOUT                 181
#define IDS_STR_EATIN                   182
#define IDS_STR_ITEM                    183
#define IDS_STR_PROCESS                 184
#define IDS_STR_CONDIMENT               185
#define IDS_STR_SPEC                    186
#define IDS_STR_LANG                    187
#define IDS_STR_LOSTSERVER              188
#define IDS_STR_SERVERIP                189
#define IDS_STR_DBERROR                 190
#define IDS_ALREADYRUN                  191
#define IDS_STR_COOKLIST                192
#define IDS_STR_TABLENAME               193
#define IDS_STR_TIMEDIFF                194
#define IDS_STR_QUANTITY_UNIT           195
#define IDS_STR_COOKCOMPLETE            196
#define IDS_STR_COMBINEORDER            197
#define IDS_STR_PENDORDER               198
#define IDS_STR_DONOTMAKE               199
#define IDS_STR_CLOSEDLG                200
#define IDS_STR_CANCELPEND              201
#define IDS_STR_ITEMNAME                202
#define IDS_STR_ONLYNAME1               203
#define IDS_STR_ONLYNAME2               204
#define IDS_STR_NAME1ANDNAME2           205
#define IDS_STR_RUSHOPEN                206
#define IDS_STR_RUSHCLOSE               207
#define IDS_STR_VERSIONLABEL            208
#define IDS_STR_TIMESECOND              209
#define IDS_STR_RUSHLABEL               210
#define IDS_STR_SETMEAL                 211
#define IDS_STR_FREE                    212
#define IDS_STR_RUSH                    213
#define IDS_STR_OUTTIME                 214
#define IDS_STR_FONT                    215
#define IDS_STR_WAIT                    215
#define IDS_STR_SERVERSETTING           216
#define IDS_STR_INVALID                 217
#define IDS_STR_RETURN                  218
#define IDS_STR_CALL                    219
#define IDS_STR_VERSIONINFO             220
#define IDS_STR_CONFIGTIP               220
#define IDS_STR_CALLTIP                 221
#define IDS_STR_PREPARE                 222
#define IDS_STR_FETCH                   223
#define IDS_STR_COOKTIME                224
#define IDS_STR_ALLPRINTCLASS           225
#define IDS_STR_DEFAULTLANG             226
#define IDS_STR_DELIVERY                226
#define IDS_STR_YES                     227
#define IDS_STR_NO                      228
#define IDS_STR_SHOWCHECKID             229
#define IDS_STR_PRINTLABEL              230
#define IDS_STR_NOTPRINT                231
#define IDS_STR_INITKITCHENTYPE         232
#define IDS_STR_NOKITCHENTYPE           233
#define IDS_STR_LOADLANGUAGE            234
#define IDC_BTN_PENDING                 1000
#define IDC_BTN_HISTORY                 1001
#define IDC_BTN_FIRST                   1002
#define IDC_BTN_PRE                     1003
#define IDC_BTN_NEXT                    1004
#define IDC_BTN_END                     1005
#define IDC_BTN_SETTING                 1006
#define IDC_BTN_CLOSE                   1007
#define IDC_BTN_COOKING                 1009
#define IDC_STATIC_VAL_ITEM             1011
#define IDC_STATIC_NUM                  1012
#define IDC_STATIC_VAL_NUM              1014
#define IDC_BTN_PEND                    1015
#define IDC_BTN_ORDER                   1016
#define IDC_BTN_DONE                    1017
#define IDC_STATIC_UNIT                 1020
#define IDC_STATIC_VAL_UNIT             1021
#define IDC_STATIC_DESC                 1022
#define IDC_STATIC_VAL_DESC             1023
#define IDC_STATIC_ORDER_REMARK         1024
#define IDC_STATIC_VAL_ORDER_REMARK     1025
#define IDC_STATIC_EATTYPE              1026
#define IDC_STATIC_VAL_EATTYPE          1027
#define IDC_STATIC_EMPLOYEE             1028
#define IDC_STATIC_VAL_EMPLOYEE         1029
#define IDC_STATIC_POS                  1030
#define IDC_STATIC_ORDER_TIME           1031
#define IDC_STATIC_CHKNUM               1032
#define IDC_STATIC_TABLE                1033
#define IDC_STATIC_CUSTNUM              1034
#define IDC_STATIC_VAL_POS              1035
#define IDC_STATIC_VAL_ORDER_TIME       1036
#define IDC_STATIC_VAL_CHKNUM           1037
#define IDC_STATIC_VAL_TABLE            1038
#define IDC_STATIC_VAL_CUSTNUM          1039
#define IDC_STATIC_AVGTIME              1041
#define IDC_STATIC_PAGENUM              1042
#define IDC_LIST_DETAIL                 1044
#define IDC_STATIC_HEADID               1045
#define IDC_STATIC_VAL_HEADID           1046
#define IDC_STATIC_CHECKID              1047
#define IDC_STATIC_VAL_CHECKID          1048
#define IDC_STATIC_ORDERTIME            1049
#define IDC_STATIC_VAL_ORDERTIME        1050
#define IDC_STATIC_MAKETIME             1051
#define IDC_STATIC_VAL_MAKETIME         1052
#define IDC_STATIC_REMARK               1053
#define IDC_STATIC_VAL_REMARK           1054
#define IDC_STATIC_KITCHEN              1055
#define IDC_STATIC_REFRESHTIME          1058
#define IDC_EDIT_REFRESHTIME            1059
#define IDC_STATIC_MODE                 1061
#define IDC_RADIO_COOK                  1062
#define IDC_RADIO_SEND                  1063
#define IDC_BTN_SAVE                    1065
#define IDC_BTN_CANCEL                  1066
#define IDC_STATIC_ORDER                1069
#define IDC_RADIO_DETIAL                1075
#define IDC_RADIO_ORDER                 1076
#define IDC_STATIC_STYLE                1077
#define IDC_BTN_RECOVERY                1078
#define IDC_STATIC_CHECK_NUMBER         1082
#define IDC_STATIC_VAL_CHKNUMBER        1083
#define IDC_STATIC_VAL_CHECKNAME        1086
#define IDC_STATIC_CHECKNAME            1087
#define IDC_COMBO_LANGUAGE              1088
#define IDC_STATIC_LANGUAGE             1089
#define IDC_BTN_SERVERIP                1090
#define IDC_STATIC_VERLABEL             1091
#define IDC_STATIC_VERSION              1092
#define IDC_BTN_LANGUAGE1               1093
#define IDC_BTN_LANGUAGE2               1094
#define IDC_BTN_LANGUAGE3               1095
#define IDC_BTN_REFRESHTIMESUBTRACT     1096
#define IDC_BTN_LANGUAGE4               1097
#define IDC_BTN_REFRESHTIMEADD          1098
#define IDC_STATIC_SECOND               1099
#define IDC_STATIC_ITEMNAME             1100
#define IDC_STATIC_RUSHLABEL            1101
#define IDC_RADIO_ONLYNAME1             1102
#define IDC_RADIO_ONLYNAME2             1103
#define IDC_RADIO_NAME1ANDNAME2         1104
#define IDC_RADIO_RUSHOPEN              1105
#define IDC_RADIO_RUSHCLOSE             1106
#define IDC_BUTTON_SERVERSET            1107
#define IDC_STATIC_SERVERSETLABEL       1108
#define IDC_BTN_COOKCOMPLETE            1109
#define IDC_RADIO_CALL                  1109
#define IDC_BTN_COMBINEORDER            1110
#define IDC_RADIO_SHOWCHECKID           1110
#define IDC_BTN_DONOTMAKE               1111
#define IDC_RADIO_HIDECHECKID           1111
#define IDC_BTN_CLOSEDLG                1112
#define IDC_STATIC_SHOWCHECKID          1112
#define IDC_BTN_PENDORDER               1113
#define IDC_STATIC_SELECTPRINT          1113
#define IDC_STATIC_LINE                 1114
#define IDC_COMBO_PRINT                 1114
#define IDC_STATIC_CHECKNAMELABEL       1115
#define IDC_STATIC_TABELNAMELABEL       1116
#define IDC_STATIC_TABELNAME            1117
#define IDC_STATIC_CUSTOMERNUMLABEL     1119
#define IDC_STATIC_CUSTOMERNUM          1120
#define IDC_STATIC_EATTYPELABEL         1121
#define IDC_STATIC_EATTYPEDETAIL        1122
#define IDC_STATIC_REMARKLABEL          1123
#define IDC_STATIC_OPENEMPLOYEENAMELABEL 1125
#define IDC_STATIC_OPENEMPLOEENAME      1126
#define IDC_STATIC_POSNAMELABEL         1127
#define IDC_STATIC_ORDERTIMELABEL       1128
#define IDC_STATIC_COMPLETETIMELABEL    1129
#define IDC_BTN_COMBINECONFIRM          1135
#define IDC_STATIC_ITEMNAME1            1136
#define IDC_STATIC_ITEMNAME2            1137
#define IDC_STATIC_DESCRIPTION          1138
#define IDC_STATIC_QUANTITY             1139
#define IDC_STATIC_WAITTIME             1140
#define IDC_CHECK_ALLITEM               1141
#define IDC_STATIC_POSNAME              1142
#define IDC_STATIC_COMPLETETIME         1143
#define IDC_STATIC_WAITPICTURE          1144
#define IDC_STATIC_SELECTPICTURE        1145
#define IDC_STATIC_RUSHPICTRUE          1146
#define IDC_STATIC_OUTTIME              1147
#define IDC_STATIC_POSITION             1148
#define IDC_BUTTON_LANGUAGE             1150

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1115
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
